#pragma once

namespace Client
{
	// 몬스터 타입
	enum MONSTERTYPE
	{
		MONSTERTYPE_SKULLSOLDIER, MONSTERTYPE_CROWSOLDIER, MONSTERTYPE_THINSOLDIER, MONSTERTYPE_NIGHTMARE, // Twlight Town
		MONSTERTYPE_SHININGEGG, MONSTERTYPE_MONKEY, MONSTERTYPE_MOWER, MONSTERTYPE_FLOWER, MONSTERTYPE_NOBODY, // Rapunzel
		MONSTERTYPE_BIGTREE, // Rapunzel_Boss
		MONSTERTYPE_BOWMAN, MONSTERTYPE_CANNON, // Toystroy
		MONSTERTYPE_ICEMAN, MONSTERTYPE_FROZENWOLF, MONSTERTYPE_SUMMONWOLF, MONSTERTYPE_GOAT, // Frozen
		MONSTERTYPE_END
	};
}